title: "Liam May"
email: N/A
description: >- # this means to ignore newlines until "baseurl:"
  This is my portfolio website!
baseurl: "/" 
url: "/" 
twitter_username: 
github_username:  

sass:
  sass_dir: 

#icon: /assets/img/icon.jpg
